# Generated by Django 3.0.5 on 2020-04-12 17:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For_Sale', max_length=20)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('des', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField(null=True)),
                ('bedroom', models.IntegerField(null=True)),
                ('bathroom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('kin_Name', models.CharField(max_length=100)),
                ('kin_phoneNumber', models.CharField(max_length=100)),
                ('kin_address', models.CharField(max_length=100)),
                ('employer_name', models.CharField(max_length=100)),
                ('employer_Address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 12, 18, 43, 34, 246458))),
                ('amount', models.IntegerField(null=True)),
                ('amount_to_be_paid', models.IntegerField(null=True)),
                ('total_paid', models.IntegerField(null=True)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Houses.Properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubBreakDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_month', models.BooleanField(default=False)),
                ('amount_paid', models.CharField(max_length=100)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Houses.Subscription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
