# Generated by Django 3.0.5 on 2020-04-12 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0005_auto_20200412_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 18, 50, 35, 640362)),
        ),
    ]
