# Generated by Django 3.0.5 on 2020-04-12 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0008_auto_20200412_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbreakdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 18, 55, 14, 490323)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 18, 55, 14, 489323)),
        ),
    ]
