# Generated by Django 3.0.5 on 2020-04-12 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0009_auto_20200412_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbreakdown',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subbreakdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 18, 57, 19, 961770)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 18, 57, 19, 961770)),
        ),
    ]
