# Generated by Django 3.0.5 on 2020-04-16 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0011_auto_20200416_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbreakdown',
            name='percentage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subbreakdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 9, 21, 2, 297765)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 9, 21, 2, 296766)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dateOfTour',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 9, 21, 2, 297765)),
        ),
    ]
