# Generated by Django 3.0.5 on 2020-04-16 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0012_auto_20200416_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbreakdown',
            name='updatedAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subbreakdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 9, 26, 54, 374867)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 9, 26, 54, 374867)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dateOfTour',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 9, 26, 54, 375883)),
        ),
    ]
