# Generated by Django 3.0.5 on 2020-04-16 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0013_auto_20200416_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbreakdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 15, 27, 41, 874969)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 15, 27, 41, 873970)),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dateOfTour',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 15, 27, 41, 874969)),
        ),
    ]
