# Generated by Django 3.0.5 on 2020-04-16 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houses', '0016_auto_20200416_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbreakdown',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 16, 32, 35, 518505)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 16, 32, 35, 517506)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='employer_Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='employer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='kin_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='kin_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='kin_phoneNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dateOfTour',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 16, 32, 35, 518505)),
        ),
    ]
